//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_A_Flat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Felhasznalo
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Email { get; set; }
        public string Cim { get; set; }
        public string Jelszo { get; set; }
        public string Telefonszam { get; set; }

        public Felhasznalo (string nev, string email, string cim, string jelszo, string telefonszam)
        {
            this.Nev = nev;
            this.Email = email;
            this.Cim = cim;
            this.Jelszo = jelszo;
            this.Telefonszam = telefonszam;
        }

        public override string ToString()
        {
            return this.Nev;
        }
    }
}
