//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_A_Flat
{
    using System;
    using System.Collections.Generic;

    public partial class Ingatlan
    {
        public int Id { get; set; }
        public string Cim { get; set; }
        public int Terulet { get; set; }
        public int Szoba { get; set; }
        public int Felszoba { get; set; }
        public string Komfort { get; set; }
        public string Futes { get; set; }
        public int Furdo { get; set; }
        public System.DateTime Epites_eve { get; set; }
        public string Parkolas { get; set; }
        public string Leiras { get; set; }
       // public string Tulajdonos { get; set; }

        public Ingatlan(string Cim, int Terulet, int Szoba, int Felszoba, string Komfort, string Futes, int Furdo, System.DateTime Epites_eve, string Parkolas, string Leiras)
            //string Tulajdonos)
        {
            
            this.Cim = Cim;
            this.Terulet = Terulet;
            this.Szoba = Szoba;
            this.Felszoba = Felszoba;
            this.Komfort = Komfort;
            this.Futes = Futes;
            this.Furdo = Furdo;
            this.Epites_eve = Epites_eve;
            this.Parkolas = Parkolas;
            this.Leiras = Leiras;
            //this.Tulajdonos = Tulajdonos;

        }
    }
}