//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_A_Flat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingatlan
    {
        public int Id { get; set; }
        public string Cim { get; set; }
        public int Terulet { get; set; }
        public int Szoba { get; set; }
        public int Felszoba { get; set; }
        public string Komfort { get; set; }
        public string Futes { get; set; }
        public int Furdo { get; set; }
        public int Epites_eve { get; set; }
        public string Parkolas { get; set; }
        public string Leiras { get; set; }
        public string Tulajdonos { get; set; }

        public Ingatlan (string cim, int terulet, int szoba, int felszoba, string komfort,
            string futes, int furdo, int epites_eve, string parkolas, string leiras, string tulajdonos)
        {
            this.Cim = cim;
            this.Terulet = terulet;
            this.Szoba = szoba;
            this.Felszoba = felszoba;
            this.Komfort = komfort;
            this.Futes = futes;
            this.Furdo = furdo;
            this.Epites_eve = epites_eve;
            this.Parkolas = parkolas;
            this.Leiras = leiras;
            this.Tulajdonos = tulajdonos;

        }
        
        }

}
